import { createContext, useContext, useState, useEffect } from "react";

const DICTIONARY = {
  English: {
    // Navigation / Sidebar
    officialAssistant: "OFFICIAL AI ASSISTANT",
    startCertification: "Start Certification",
    home: "Home",
    assistant: "AI Assistant",
    standards: "Standards",
    certification: "Certification",
    labs: "Testing Labs",
    hallmarking: "Hallmarking",
    recentChats: "Recent Chats",
    chat: "Chat",
    chatOptions: "Chat options",
    shareConversation: "Share conversation",
    pin: "Pin",
    rename: "Rename",
    delete: "Delete",
    newChat: "New Chat",
    profile: "Profile",
    help: "Help",
    logout: "Logout",

    // Home Dashboard
    welcomeBack: "Welcome back",
    greetingUser: "Hi, {name}",
    heroTitle: "How can I help you today?",
    heroSubtitle: "Ask about ISI Mark, HUID, or search standards.",
    searchPlaceholder: "e.g., How to apply for ISI mark for cement?",
    quickServices: "Quick Services",
    quickAccessSub: "Quick access to BIS services",
    verifyHuidTitle: "Verify HUID",
    verifyHuidDesc: "Check authenticity of hallmarked jewellery.",
    checkIsMarkTitle: "Check IS Mark",
    checkIsMarkDesc: "Verify licenses and IS mark validity.",
    testingLabsTitle: "Testing Labs",
    testingLabsDesc: "Search labs to verify product standards.",
    certHelpTitle: "Cert Help",
    certHelpDesc: "Guide for certification process.",
    explore: "Explore",
    newsAmendments: "News & Amendments",
    latestUpdatesSub: "Latest updates and amendments",
    viewAll: "View All",
    recentActivity: "Recent Activity",
    latestActivitySub: "Your latest activity",
    viewAllHistory: "View All History",
    loadingDashboard: "Loading dashboard & updates...",
    alert: "ALERT",
    update: "UPDATE",
    defaultNews1Title: "Mandatory Certification for Footwear",
    defaultNews1Summary:
      "QCO implementation date for footwear products extended. Check updated guidelines for compliance.",
    defaultNews2Title: "Revision of IS 10500: Drinking Water",
    defaultNews2Summary:
      "New amendments published regarding heavy metal limits. Effective from next month.",
    defaultAct1Title: "IS 1293: Plugs and Socket-Outlets",
    defaultAct1Desc: "Viewed standard details and testing requirements.",
    defaultAct1Time: "2 hours ago",
    defaultAct2Title: '"What is the fee for factory inspection?"',
    defaultAct2Desc: "AI Assistant chat query regarding Scheme-I.",
    defaultAct2Time: "Yesterday",
    defaultAct3Title: "IS 456: Plain and Reinforced Concrete",
    defaultAct3Desc: "Downloaded PDF document.",
    defaultAct3Time: "Oct 21, 2023",

    // Profile & Settings
    profileTitle: "Profile & Settings",
    profileSubtitle: "Manage your personal account details and preferences",
    registeredUser: "Registered User",
    noEmail: "No email on file",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    basicInfoTitle: "Basic Personal Information",
    basicInfoSubtitle: "Your personal contact and identity details",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    addPhoneNumber: "Add phone number",
    location: "Location (Optional)",
    locationPlaceholder: "e.g. New Delhi, India",
    saveChanges: "Save Changes",
    saving: "Saving…",
    saved: "Saved",
    close: "Close",
    preferencesTitle: "Preferences",
    preferencesSubtitle: "Customize your assistant experience",
    prefLanguage: "Preferred Language",
    prefLanguageDesc: "Select the primary language for interactions and reports",
    notifications: "Notifications",
    notificationsDesc: "Receive updates and alerts regarding your queries",
    securityTitle: "Account & Security",
    securitySubtitle: "Manage your authentication and view legal terms",
    changePassword: "Change Password",
    privacyPolicy: "Privacy Policy",
    termsConditions: "Terms & Conditions",
    retry: "Retry",
    loadErrorFallback: "Couldn't load your profile.",
    saveErrorFallback: "Couldn't save your changes.",

    // AI Assistant
    assistantGreeting: "How can I help you today?",
    assistantSubtext:
      "Ask about Indian Standards, certification, ISI Mark, HUID, testing requirements, or BIS services.",
    assistantInputPlaceholder:
      "Ask about standards, certification processes, or upload documents for review...",
    docPlaceholder: "Ask something about the selected document...",
    sourcesCount: "Sources",
    reference: "Reference",
    openLink: "Open Link",
    queryingRegistry: "BIS Sahayak is querying standards registry...",
    preparingChat: "Preparing your secure conversation...",
    initChatError: "Failed to initialize conversation.",
    newChatError: "Unable to create a new conversation.",
    sessionNotReady: "Conversation session is not ready.",
    mlError: "Failed to process ML response.",
    voiceSupportError: "Voice recognition is only supported in Chrome/Edge.",
    voiceInputError: "Voice input error. Check microphone permissions.",
    fileSizeError: "File size must be under 10 MB.",
    q1: "What are the main activities of BIS?",
    q2: "What is the ISI Mark?",
    q3: "Show me standards for plugs and sockets",

    // Certification Page
    complianceRoadmap: "Compliance Journey Roadmap",
    certificationSubtitle:
      "Certification Steps, Milestones, and Clause Requirements",
    completed: "Completed",
    currentStep: "Current Step",
    pendingPrevious: "Pending previous milestone",
    acknowledge: "Acknowledge",
    viewDetails: "View Details",
    keyRequirements: "Key Requirements",
    referenceClauses: "Reference Clauses",
    downloadChecklist: "Download Checklist",
    connectExpert: "Connect with Expert",

    // Standards Page
    searchStandardsPlaceholder: "Search standards, e.g. Water Purifiers",
    filtersLabel: "FILTERS:",
    mandatory: "Mandatory",
    voluntary: "Voluntary",
    draft: "Draft",
    moreFilters: "More Filters",
    searchResults: "Search Results",
    searchPrompt: "Search above to find applicable standards.",
    sortBy: "Sort by:",
    relevance: "Relevance",
    searchingDb: "Searching standards database...",
    fetchingStandards: "Fetching latest standards...",
    noStandardsFound: "No standards found",
    adjustFilters: "Try a different search term or adjust your filters.",
    standardsSearchNotLive: "Standards search isn't live yet — waiting on the backend endpoint.",
    foundResultsText: "Found {total} standard{plural} related to '{query}'",

    // Verification Center (legacy naming, still referenced on the Home dashboard)
    verificationCenter: "BIS Verification Center",
    goldHuidTab: "Gold HUID",
    bisLicenseTab: "BIS License",
    verifyHuidHeading: "Verify Gold Jewellery HUID",
    verifyHuidSub: "Enter the 6-digit alphanumeric Hallmark Unique ID stamped on gold jewellery.",
    huidInputPlaceholder: "HUID Code",
    sampleCodeLabel: "Sample code:",
    verifyHuidBtn: "Verify HUID",
    verifyLicenseHeading: "Verify BIS License / ISI Mark",
    verifyLicenseSub: "Enter the Manufacturer License Number (CM/L) to verify product certification.",
    licenseInputPlaceholder: "License Number (CM/L)",
    sampleLicenseLabel: "Sample license:",
    verifyLicenseBtn: "Verify License",
    verifying: "Verifying…",

    // Auth & Landing
    govtOfIndia: "GOVT. OF INDIA",
    empoweringStandards1: "Empowering",
    empoweringStandards2: "Indian Standards",
    authHeroSubtext: "A secure, streamlined platform for authorized personnel and registered technical partners of the Bureau of Indian Standards.",
    govtGradeSecurity: "Govt. Grade Security",
    troubleSigningIn: "Trouble signing in?",
    troubleSigningUp: "Trouble signing up?",
    officialBisPortal: "Official BIS Portal",
    orDivider: "OR",
    namaste: "Namaste",
    signInSubtitle: "Sign in to your BIS Sahayak account",
    emailLabel: "EMAIL ADDRESS",
    passwordLabel: "PASSWORD",
    confirmPasswordLabel: "CONFIRM PASSWORD",
    fullNameLabel: "FULL NAME",
    preferredLanguageLabel: "PREFERRED LANGUAGE",
    signInBtn: "Sign In",
    signingInBtn: "Signing in...",
    signUpBtn: "Sign Up",
    sendOtpBtn: "Send OTP",
    creatingAccountBtn: "Creating account...",
    createAccountTitle: "Create Account",
    createAccountSubtitle: "Register for your BIS Sahayak account",
    alreadyHaveAccountSignIn: "Already have an account? Sign In",

    // Compliance Journey (Certification.jsx)
    complianceJourneyLabel: "Compliance Journey",
    prodComplianceJourneyTitle: "Product Compliance Journey",
    prodComplianceJourneySub:
      "Select a product to understand its current compliance stage and the steps required for certification.",
    overallProgress: "Overall Progress",
    stagesCompletedSummary: "{completed} of {total} stages completed",
    selectProductHeading: "Select Product",
    viewComplianceJourney: "View compliance journey",
    loadingProducts: "Loading compliance products...",
    loadingJourney: "Loading compliance journey...",
    selectedProductLabel: "Selected Product",
    complianceTimelineTitle: "Compliance Timeline",
    complianceTimelineSub: "Track every stage of the product compliance process.",
    noStagesTitle: "No stages available",
    noStagesSub: "No compliance stages were returned for this product.",
    noJourneyTitle: "No compliance journey available",
    noJourneySub: "We couldn't load the compliance journey for this product.",
    stageLabel: "Stage",
    stageUnlockedNotice: "This stage will unlock after previous requirements are completed.",
    inProgressBadge: "In Progress",
    pendingBadge: "Pending",
    completedBadge: "Completed",
    askAiAssistantBtn: "Ask AI Assistant",

    // Testing Labs Locator (TestingLabs.jsx)
    testingLabsLabel: "Testing Labs",
    centreLocatorTitle: "BIS Centre Locator",
    centreLocatorSub: "Find nearby BIS testing centres and laboratories using your city or location.",
    locationInputPlaceholder: "Enter city or location",
    findCentresBtn: "Find Centres",
    findingBtn: "Finding...",
    locationRequiredErr: "Location is required",
    nearbyCentresMapTitle: "Nearby BIS Centres",
    showingCentresSub: "Showing centres within 25 km",
    locationFoundLabel: "Location found",
    searchedLocationPopup: "Your searched location",
    searchLocationPlaceholderPrompt: "Search for a location",
    searchLocationPromptSub: "Enter your city above to see nearby BIS centres on the map.",
    centreDetailsTitle: "Centre Details",
    centresFoundCount: "{count} centre{plural} found",
    searchToFindNearby: "Search to find nearby centres",
    noCentresTitle: "No centres to show",
    noCentresSub: "Enter a city or location and click \"Find Centres\" to search nearby BIS facilities.",
    servicesSubheading: "Services",
    notAvailable: "Not available",

    // Verification Services (Verification.jsx)
    statusLabel: "Status",
    verificationServicesLabel: "Verification Services",
    verifyBisInfoTitle: "Verify BIS Information",
    verifyBisInfoSub: "Verify HUID numbers and BIS licences to check authenticity and available certification details.",
    previewSampleDetails: "Preview sample details",
    huidVerificationTitle: "HUID Verification",
    huidVerificationSub: "Verify the authenticity of a jewellery HUID number.",
    enterHuidPlaceholder: "Enter 6-digit HUID code (e.g. A8F2X9)",
    huidEmptyErr: "Please enter a HUID number.",
    verifyHuidActionBtn: "Verify HUID",
    huidValidTitle: "HUID is Valid",
    huidInvalidTitle: "HUID is Invalid",
    huidNumberLabel: "HUID Number",
    jewelleryTypeLabel: "Jewellery Type",
    purityLabel: "Purity",
    metalLabel: "Metal",
    jewellerLabel: "Jeweller",
    bisRegLabel: "BIS Registration",
    verificationDateLabel: "Verification Date",
    verificationInfoHeading: "Verification Information",
    licenceVerificationTitle: "BIS Licence Verification",
    licenceVerificationSub: "Verify a BIS licence and view available licence details.",
    enterLicencePlaceholder: "Enter BIS licence number (e.g. CM/L-1234567)",
    licenceEmptyErr: "Please enter a BIS licence number.",
    verifyLicenceActionBtn: "Verify Licence",
    licenceNotFoundTitle: "Licence Not Found",
    licenceValidTitle: "Licence is Valid",
    licenceInvalidTitle: "Licence is Invalid",
    licenceNumberLabel: "Licence Number",
    licenceHolderLabel: "Licence Holder",
    productLabel: "Product",
    standardLabel: "Standard",
    manufacturerLabel: "Manufacturer",
    issueDateLabel: "Issue Date",
    expiryDateLabel: "Expiry Date",
    validStatusText: "VALID",
    invalidStatusText: "INVALID",
    detailsAvailableMsg: "The verification details are available below.",
    couldNotVerifyMsg: "The provided information could not be verified.",
  },
  Hindi: {
    // Navigation / Sidebar
    officialAssistant: "आधिकारिक एआई सहायक",
    startCertification: "प्रमाणीकरण शुरू करें",
    home: "होम",
    assistant: "एआई सहायक",
    standards: "मानक",
    certification: "प्रमाणीकरण",
    labs: "परीक्षण प्रयोगशालाएं",
    hallmarking: "हॉलमार्किंग",
    recentChats: "हाल की बातचीत",
    chat: "बातचीत",
    chatOptions: "चैट विकल्प",
    shareConversation: "बातचीत साझा करें",
    pin: "पिन करें",
    rename: "नाम बदलें",
    delete: "हटाएं",
    newChat: "नई चैट",
    profile: "प्रोफ़ाइल",
    help: "सहायता",
    logout: "लॉगआउट",

    // Home Dashboard
    welcomeBack: "वापसी पर स्वागत है",
    greetingUser: "नमस्ते, {name}",
    heroTitle: "आज मैं आपकी क्या मदद कर सकता हूँ?",
    heroSubtitle: "आईएसआई मार्क, एचयूआईडी या भारतीय मानकों के बारे में पूछें।",
    searchPlaceholder: "उदा. सीमेंट के लिए आईएसआई मार्क हेतु आवेदन कैसे करें?",
    quickServices: "त्वरित सेवाएं",
    quickAccessSub: "बीआईएस सेवाओं तक त्वरित पहुंच",
    verifyHuidTitle: "एचयूआईडी सत्यापित करें",
    verifyHuidDesc: "हॉलमार्क वाले आभूषणों की प्रामाणिकता जांचें।",
    checkIsMarkTitle: "आईएस मार्क जांचें",
    checkIsMarkDesc: "लाइसेंस और आईएस मार्क की वैधता सत्यापित करें।",
    testingLabsTitle: "परीक्षण प्रयोगशालाएं",
    testingLabsDesc: "उत्पाद मानकों को सत्यापित करने के लिए प्रयोगशालाएं खोजें।",
    certHelpTitle: "प्रमाणीकरण सहायता",
    certHelpDesc: "प्रमाणीकरण प्रक्रिया के लिए मार्गदर्शिका।",
    explore: "देखें",
    newsAmendments: "समाचार एवं संशोधन",
    latestUpdatesSub: "नवीनतम अपडेट और संशोधन",
    viewAll: "सभी देखें",
    recentActivity: "हाल की गतिविधि",
    latestActivitySub: "आपकी हाल की गतिविधि",
    viewAllHistory: "संपूर्ण इतिहास देखें",
    loadingDashboard: "डैशबोर्ड और अपडेट लोड हो रहे हैं...",
    alert: "सूचना",
    update: "अपडेट",
    defaultNews1Title: "फुटवियर के लिए अनिवार्य प्रमाणीकरण",
    defaultNews1Summary:
      "फुटवियर उत्पादों के लिए क्यूसीओ कार्यान्वयन तिथि बढ़ाई गई। अनुपालन दिशानिर्देश देखें।",
    defaultNews2Title: "आईएस 10500 का संशोधन: पीने का पानी",
    defaultNews2Summary:
      "भारी धातु सीमाओं के संबंध में नए संशोधन प्रकाशित। अगले महीने से प्रभावी।",
    defaultAct1Title: "आईएस 1293: प्लग और सॉकेट-आउटलेट",
    defaultAct1Desc: "मानक विवरण और परीक्षण आवश्यकताएं देखी गईं।",
    defaultAct1Time: "2 घंटे पहले",
    defaultAct2Title: '"कारखाना निरीक्षण शुल्क कितना है?"',
    defaultAct2Desc: "स्कीम-I के संबंध में एआई सहायक से की गई चैट।",
    defaultAct2Time: "कल",
    defaultAct3Title: "आईएस 456: सादा और प्रबलित कंक्रीट",
    defaultAct3Desc: "पीडीएफ दस्तावेज़ डाउनलोड किया गया।",
    defaultAct3Time: "21 अक्टूबर 2023",

    // Profile & Settings
    profileTitle: "प्रोफ़ाइल और सेटिंग्स",
    profileSubtitle: "अपने व्यक्तिगत खाते के विवरण और प्राथमिकताओं का प्रबंधन करें",
    registeredUser: "पंजीकृत उपयोगकर्ता",
    noEmail: "कोई ईमेल दर्ज नहीं है",
    editProfile: "प्रोफ़ाइल संपादित करें",
    cancel: "रद्द करें",
    basicInfoTitle: "मूल व्यक्तिगत जानकारी",
    basicInfoSubtitle: "आपके व्यक्तिगत संपर्क और पहचान विवरण",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फ़ोन नंबर",
    addPhoneNumber: "फ़ोन नंबर जोड़ें",
    location: "स्थान (वैकल्पिक)",
    locationPlaceholder: "उदा. नई दिल्ली, भारत",
    saveChanges: "बदलाव सहेजें",
    saving: "सहेजा जा रहा है…",
    saved: "सहेजा गया",
    close: "बंद करें",
    preferencesTitle: "प्राथमिकताएं",
    preferencesSubtitle: "अपने सहायक अनुभव को अनुकूलित करें",
    prefLanguage: "पसंदीदा भाषा",
    prefLanguageDesc: "बातचीत और रिपोर्ट के लिए प्राथमिक भाषा चुनें",
    notifications: "सूचनाएं",
    notificationsDesc: "अपने प्रश्नों के संबंध में अपडेट और अलर्ट प्राप्त करें",
    securityTitle: "खाता और सुरक्षा",
    securitySubtitle: "अपने प्रमाणीकरण का प्रबंधन करें और कानूनी शर्तें देखें",
    changePassword: "पासवर्ड बदलें",
    privacyPolicy: "गोपनीयता नीति",
    termsConditions: "नियम और शर्तें",
    retry: "पुनः प्रयास करें",
    loadErrorFallback: "आपकी प्रोफ़ाइल लोड नहीं हो सकी।",
    saveErrorFallback: "आपके बदलाव सहेजे नहीं जा सके।",

    // AI Assistant
    assistantGreeting: "आज मैं आपकी क्या मदद कर सकता हूँ?",
    assistantSubtext:
      "भारतीय मानकों, प्रमाणीकरण, आईएसआई मार्क, एचयूआईडी, परीक्षण आवश्यकताओं या बीआईएस सेवाओं के बारे में पूछें।",
    assistantInputPlaceholder:
      "मानकों, प्रमाणीकरण प्रक्रियाओं के बारे में पूछें, या समीक्षा के लिए दस्तावेज़ अपलोड करें...",
    docPlaceholder: "चयनित दस्तावेज़ के बारे में कुछ पूछें...",
    sourcesCount: "स्रोत",
    reference: "संदर्भ",
    openLink: "लिंक खोलें",
    queryingRegistry: "बीआईएस सहायक मानक रजिस्ट्री खोज रहा है...",
    preparingChat: "आपकी सुरक्षित बातचीत तैयार की जा रही है...",
    initChatError: "बातचीत प्रारंभ करने में विफल।",
    newChatError: "नई बातचीत शुरू करने में असमर्थ।",
    sessionNotReady: "बातचीत सत्र तैयार नहीं है।",
    mlError: "प्रतिक्रिया संसाधित करने में विफल।",
    voiceSupportError: "आवाज़ पहचान केवल क्रोम या एज ब्राउज़र में समर्थित है।",
    voiceInputError: "माइक्रोफ़ोन त्रुटि। अनुमतियों की जाँच करें।",
    fileSizeError: "फ़ाइल का आकार 10 एमबी से कम होना चाहिए।",
    q1: "बीआईएस की मुख्य गतिविधियाँ क्या हैं?",
    q2: "आईएसआई मार्क क्या है?",
    q3: "प्लग और सॉकेट के मानक दिखाएं",

    // Certification Page
    complianceRoadmap: "अनुपालन यात्रा रोडमैप",
    certificationSubtitle: "प्रमाणीकरण चरण, मील के पत्थर और खंड आवश्यकताएं",
    completed: "पूर्ण",
    currentStep: "वर्तमान चरण",
    pendingPrevious: "पिछला चरण लंबित है",
    acknowledge: "स्वीकार करें",
    viewDetails: "विवरण देखें",
    keyRequirements: "मुख्य आवश्यकताएं",
    referenceClauses: "संदर्भ खंड",
    downloadChecklist: "चेकलिस्ट डाउनलोड करें",
    connectExpert: "विशेषज्ञ से जुड़ें",

    // Standards Page
    searchStandardsPlaceholder: "मानक खोजें, उदा. वॉटर प्यूरीफायर",
    filtersLabel: "फ़िल्टर:",
    mandatory: "अनिवार्य",
    voluntary: "स्वैच्छिक",
    draft: "प्रारूप (ड्राफ्ट)",
    moreFilters: "अन्य फ़िल्टर",
    searchResults: "खोज परिणाम",
    searchPrompt: "लागू मानकों को खोजने के लिए ऊपर खोजें।",
    sortBy: "क्रमबद्ध करें:",
    relevance: "प्रासंगिकता",
    searchingDb: "मानक डेटाबेस खोजा जा रहा है...",
    fetchingStandards: "नवीनतम मानक प्राप्त किए जा रहे हैं...",
    noStandardsFound: "कोई मानक नहीं मिला",
    adjustFilters: "भिन्न खोज शब्द का प्रयास करें या अपने फ़िल्टर समायोजित करें।",
    standardsSearchNotLive: "मानक खोज अभी लाइव नहीं है — बैकएंड एंडपॉइंट की प्रतीक्षा है।",
    foundResultsText: "'{query}' से संबंधित {total} मानक मिले",

    // Verification Center (legacy naming, still referenced on the Home dashboard)
    verificationCenter: "बीआईएस सत्यापन केंद्र",
    goldHuidTab: "गोल्ड एचयूआईडी",
    bisLicenseTab: "बीआईएस लाइसेंस",
    verifyHuidHeading: "सोने के आभूषण एचयूआईडी सत्यापित करें",
    verifyHuidSub: "सोने के आभूषणों पर अंकित 6 अंकों का अल्फ़ान्यूमेरिक हॉलमार्क विशिष्ट पहचान कोड दर्ज करें।",
    huidInputPlaceholder: "एचयूआईडी कोड",
    sampleCodeLabel: "नमूना कोड:",
    verifyHuidBtn: "एचयूआईडी सत्यापित करें",
    verifyLicenseHeading: "बीआईएस लाइसेंस / आईएसआई मार्क सत्यापित करें",
    verifyLicenseSub: "उत्पाद प्रमाणीकरण सत्यापित करने के लिए निर्माता लाइसेंस संख्या (CM/L) दर्ज करें।",
    licenseInputPlaceholder: "लाइसेंस संख्या (CM/L)",
    sampleLicenseLabel: "नमूना लाइसेंस:",
    verifyLicenseBtn: "लाइसेंस सत्यापित करें",
    verifying: "सत्यापित किया जा रहा है…",

    // Auth & Landing
    govtOfIndia: "भारत सरकार",
    empoweringStandards1: "सशक्त",
    empoweringStandards2: "भारतीय मानक",
    authHeroSubtext: "भारतीय मानक ब्यूरो के अधिकृत कर्मियों और पंजीकृत तकनीकी भागीदारों के लिए एक सुरक्षित, सुव्यवस्थित मंच।",
    govtGradeSecurity: "सरकारी स्तर की सुरक्षा",
    troubleSigningIn: "साइन इन करने में समस्या आ रही है?",
    troubleSigningUp: "साइन अप करने में समस्या आ रही है?",
    officialBisPortal: "आधिकारिक बीआईएस पोर्टल",
    orDivider: "या",
    namaste: "नमस्ते",
    signInSubtitle: "अपने बीआईएस सहायक खाते में साइन इन करें",
    emailLabel: "ईमेल पता",
    passwordLabel: "पासवर्ड",
    confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
    fullNameLabel: "पूरा नाम",
    preferredLanguageLabel: "पसंदीदा भाषा",
    signInBtn: "साइन इन करें",
    signingInBtn: "साइन इन हो रहा है...",
    signUpBtn: "साइन अप करें",
    sendOtpBtn: "ओटीपी भेजें",
    creatingAccountBtn: "खाता बनाया जा रहा है...",
    createAccountTitle: "खाता बनाएं",
    createAccountSubtitle: "अपने बीआईएस सहायक खाते के लिए पंजीकरण करें",
    alreadyHaveAccountSignIn: "क्या आपके पास पहले से खाता है? साइन इन करें",

    // Compliance Journey (Certification.jsx)
    complianceJourneyLabel: "अनुपालन यात्रा",
    prodComplianceJourneyTitle: "उत्पाद अनुपालन यात्रा",
    prodComplianceJourneySub: "उत्पाद के वर्तमान अनुपालन चरण और प्रमाणीकरण के आवश्यक चरणों को समझने के लिए एक उत्पाद चुनें।",
    overallProgress: "कुल प्रगति",
    stagesCompletedSummary: "{total} में से {completed} चरण पूर्ण",
    selectProductHeading: "उत्पाद चुनें",
    viewComplianceJourney: "अनुपालन यात्रा देखें",
    loadingProducts: "अनुपालन उत्पाद लोड हो रहे हैं...",
    loadingJourney: "अनुपालन यात्रा लोड हो रही है...",
    selectedProductLabel: "चयनित उत्पाद",
    complianceTimelineTitle: "अनुपालन समयरेखा",
    complianceTimelineSub: "उत्पाद अनुपालन प्रक्रिया के प्रत्येक चरण को ट्रैक करें।",
    noStagesTitle: "कोई चरण उपलब्ध नहीं है",
    noStagesSub: "इस उत्पाद के लिए कोई अनुपालन चरण प्राप्त नहीं हुआ।",
    noJourneyTitle: "कोई अनुपालन यात्रा उपलब्ध नहीं है",
    noJourneySub: "हम इस उत्पाद के लिए अनुपालन यात्रा लोड नहीं कर सके।",
    stageLabel: "चरण",
    stageUnlockedNotice: "यह चरण पिछले आवश्यकताओं के पूरा होने के बाद अनलॉक होगा।",
    inProgressBadge: "प्रगति पर है",
    pendingBadge: "लंबित",
    completedBadge: "पूर्ण",
    askAiAssistantBtn: "एआई सहायक से पूछें",

    // Testing Labs Locator (TestingLabs.jsx)
    testingLabsLabel: "परीक्षण प्रयोगशालाएं",
    centreLocatorTitle: "बीआईएस केंद्र लोकेटर",
    centreLocatorSub: "अपने शहर या स्थान का उपयोग करके पास के बीआईएस परीक्षण केंद्रों और प्रयोगशालाओं को खोजें।",
    locationInputPlaceholder: "शहर या स्थान दर्ज करें",
    findCentresBtn: "केंद्र खोजें",
    findingBtn: "खोजा जा रहा है...",
    locationRequiredErr: "स्थान दर्ज करना अनिवार्य है",
    nearbyCentresMapTitle: "निकटवर्ती बीआईएस केंद्र",
    showingCentresSub: "25 किमी के दायरे में केंद्र प्रदर्शित हो रहे हैं",
    locationFoundLabel: "स्थान मिल गया",
    searchedLocationPopup: "आपका खोजा गया स्थान",
    searchLocationPlaceholderPrompt: "स्थान की खोज करें",
    searchLocationPromptSub: "मानचित्र पर पास के बीआईएस केंद्रों को देखने के लिए ऊपर अपना शहर दर्ज करें।",
    centreDetailsTitle: "केंद्र विवरण",
    centresFoundCount: "{count} केंद्र मिले",
    searchToFindNearby: "पास के केंद्रों को खोजने के लिए खोजें",
    noCentresTitle: "दिखाने के लिए कोई केंद्र नहीं",
    noCentresSub: "निकटवर्ती बीआईएस सुविधाओं को खोजने के लिए शहर या स्थान दर्ज करें और 'केंद्र खोजें' पर क्लिक करें।",
    servicesSubheading: "सेवाएं",
    notAvailable: "उपलब्ध नहीं",

    // Verification Services (Verification.jsx)
    statusLabel: "स्थिति",
    verificationServicesLabel: "सत्यापन सेवाएं",
    verifyBisInfoTitle: "बीआईएस जानकारी सत्यापित करें",
    verifyBisInfoSub: "प्रामाणिकता और उपलब्ध प्रमाणीकरण विवरण की जांच करने के लिए एचयूआईडी नंबर और बीआईएस लाइसेंस सत्यापित करें।",
    previewSampleDetails: "नमूना विवरण देखें",
    huidVerificationTitle: "एचयूआईडी सत्यापन",
    huidVerificationSub: "आभूषण के एचयूआईडी नंबर की प्रामाणिकता सत्यापित करें।",
    enterHuidPlaceholder: "6 अंकों का एचयूआईडी कोड दर्ज करें (उदा. A8F2X9)",
    huidEmptyErr: "कृपया एक एचयूआईडी नंबर दर्ज करें।",
    verifyHuidActionBtn: "एचयूआईडी सत्यापित करें",
    huidValidTitle: "एचयूआईडी मान्य है",
    huidInvalidTitle: "एचयूआईडी अमान्य है",
    huidNumberLabel: "एचयूआईडी नंबर",
    jewelleryTypeLabel: "आभूषण का प्रकार",
    purityLabel: "शुद्धता",
    metalLabel: "धातु",
    jewellerLabel: "जौहरी",
    bisRegLabel: "बीआईएस पंजीकरण",
    verificationDateLabel: "सत्यापन तिथि",
    verificationInfoHeading: "सत्यापन जानकारी",
    licenceVerificationTitle: "बीआईएस लाइसेंस सत्यापन",
    licenceVerificationSub: "बीआईएस लाइसेंस सत्यापित करें और उपलब्ध लाइसेंस विवरण देखें।",
    enterLicencePlaceholder: "बीआईएस लाइसेंस नंबर दर्ज करें (उदा. CM/L-1234567)",
    licenceEmptyErr: "कृपया एक बीआईएस लाइसेंस नंबर दर्ज करें।",
    verifyLicenceActionBtn: "लाइसेंस सत्यापित करें",
    licenceNotFoundTitle: "लाइसेंस नहीं मिला",
    licenceValidTitle: "लाइसेंस मान्य है",
    licenceInvalidTitle: "लाइसेंस अमान्य है",
    licenceNumberLabel: "लाइसेंस नंबर",
    licenceHolderLabel: "लाइसेंस धारक",
    productLabel: "उत्पाद",
    standardLabel: "मानक",
    manufacturerLabel: "निर्माता",
    issueDateLabel: "जारी करने की तिथि",
    expiryDateLabel: "समाप्ति तिथि",
    validStatusText: "मान्य",
    invalidStatusText: "अमान्य",
    detailsAvailableMsg: "सत्यापन विवरण नीचे उपलब्ध हैं।",
    couldNotVerifyMsg: "प्रदान की गई जानकारी सत्यापित नहीं की जा सकी।",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("preferred_language") || "English"
  );

  useEffect(() => {
    const handleSync = () => {
      setLanguage(localStorage.getItem("preferred_language") || "English");
    };
    window.addEventListener("languageChange", handleSync);
    window.addEventListener("storage", handleSync);
    return () => {
      window.removeEventListener("languageChange", handleSync);
      window.removeEventListener("storage", handleSync);
    };
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("preferred_language", lang);
    window.dispatchEvent(new Event("languageChange"));
  };

  const t = (key, params = {}) => {
    let str = DICTIONARY[language]?.[key] || DICTIONARY.English[key] || key;
    Object.keys(params).forEach((k) => {
      str = str.replace(`{${k}}`, params[k]);
    });
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);